/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package constants.programs;

import client.MapleCharacter;
import client.MapleClient;
import constants.ServerConstants;
import database.MYSQL;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TimerTask;
import java.util.concurrent.ScheduledFuture;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import launch.ChannelServer;
import launch.world.WorldBroadcasting;
import launch.world.WorldCommunity;
import packet.creators.MainPacketCreator;
import packet.creators.UIPacket;
import packet.opcode.RecvPacketOpcode;
import packet.opcode.SendPacketOpcode;
import server.maps.MapleMap;
import tools.Timer;

/**
 *
 * @author Administrator
 */
public class ControlUnit extends javax.swing.JFrame {

    private static final long serialVersionUID = -3687743956730844060L;

    public ControlUnit() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width - 1505) / 2, (screenSize.height - 576) / 2);
        initComponents();
        서버정보불러오기();
        환율정보();
        채팅금지();
        벤();
        this.setTitle("[ArcStoryDEV]Server_Emulator :: V1.2." + ServerConstants.MAPLE_VERSION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        jjj = new javax.swing.JLabel();
        meso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        drop = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        noticMessage = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        hottime = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        serverMessage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chat = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        mesos = new javax.swing.JLabel();
        realcash = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        동시접속자 = new javax.swing.JList();
        jLabel18 = new javax.swing.JLabel();
        접속자수 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1136, 607));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Give Real CASH");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(464, 26, 141, 61);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Name");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(304, 40, 154, 14);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Point");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(304, 67, 154, 14);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<REAL CASH POINT>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(304, 12, 142, 18);

        jLabel2.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<Set GM>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(304, 98, 88, 15);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Name");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(304, 124, 154, 14);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Set GM");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(464, 124, 141, 19);

        jLabel3.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<Give Item>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(304, 165, 80, 15);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Name");
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(304, 186, 154, 14);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Give Item");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(464, 186, 141, 50);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Item Code,Amount");
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(304, 212, 154, 14);

        jLabel4.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<Give Meso>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(304, 254, 89, 15);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Name");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(304, 275, 154, 14);

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Amount of Meso");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(304, 304, 154, 14);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Give Meso");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(464, 275, 141, 51);

        jLabel5.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<User Ban>");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(304, 337, 129, 15);

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("account");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(304, 359, 154, 14);

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("reason");
        jTextField9.setBorder(null);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(304, 388, 154, 14);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Ban");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(464, 358, 63, 52);

        jLabel6.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<Ban Chat>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(304, 435, 86, 15);

        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("Name");
        jTextField10.setBorder(null);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(304, 457, 154, 14);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Ban Chat");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(464, 456, 141, 19);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("UnBan Chat");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(304, 485, 301, 19);

        jLabel7.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<Freeze Chat>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(304, 514, 141, 15);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Freeze Server Chat");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(304, 535, 301, 34);

        jLabel8.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<Server Settings>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 14, 118, 15);

        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("EXP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 40, 48, 14);

        exp.setBackground(new java.awt.Color(0, 0, 0));
        exp.setForeground(new java.awt.Color(255, 255, 255));
        exp.setText("경험치");
        exp.setBorder(null);
        getContentPane().add(exp);
        exp.setBounds(33, 67, 33, 14);

        jjj.setForeground(new java.awt.Color(255, 51, 51));
        jjj.setText("MESO");
        getContentPane().add(jjj);
        jjj.setBounds(120, 40, 50, 14);

        meso.setBackground(new java.awt.Color(0, 0, 0));
        meso.setForeground(new java.awt.Color(255, 255, 255));
        meso.setText("메소");
        meso.setBorder(null);
        getContentPane().add(meso);
        meso.setBounds(126, 67, 48, 14);

        jLabel10.setForeground(new java.awt.Color(255, 0, 204));
        jLabel10.setText("DROP");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 40, 50, 14);

        drop.setBackground(new java.awt.Color(0, 0, 0));
        drop.setForeground(new java.awt.Color(255, 255, 255));
        drop.setText("드롭");
        drop.setBorder(null);
        getContentPane().add(drop);
        drop.setBounds(232, 67, 22, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Server Message ( Server Top Message )");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(22, 98, 256, 14);

        jLabel12.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("<Notify>");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 186, 88, 15);

        noticMessage.setBackground(new java.awt.Color(0, 0, 0));
        noticMessage.setForeground(new java.awt.Color(255, 255, 255));
        noticMessage.setText("enter notifying message here");
        noticMessage.setBorder(null);
        noticMessage.setMaximumSize(new java.awt.Dimension(6, 21));
        noticMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticMessageActionPerformed(evt);
            }
        });
        getContentPane().add(noticMessage);
        noticMessage.setBounds(20, 207, 273, 14);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setText("popup");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 230, 60, 19);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setForeground(new java.awt.Color(255, 0, 204));
        jButton10.setText("pink");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(80, 230, 70, 19);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 204, 51));
        jButton11.setText("showinfo");
        jButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(150, 230, 90, 20);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setForeground(new java.awt.Color(153, 0, 204));
        jButton12.setText("npc");
        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(240, 230, 60, 19);

        jLabel13.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("<Hot Time>");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 277, 90, 15);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Apply Server Changes");
        jButton14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(22, 153, 273, 19);

        hottime.setBackground(new java.awt.Color(0, 0, 0));
        hottime.setForeground(new java.awt.Color(255, 255, 255));
        hottime.setText("Item Code,Amount");
        hottime.setBorder(null);
        getContentPane().add(hottime);
        hottime.setBounds(20, 304, 168, 14);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("give Hot time");
        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(194, 303, 90, 19);

        jLabel14.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("<Server Features>");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 337, 190, 15);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Save ALL Server");
        jButton15.setToolTipText("");
        jButton15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(10, 358, 282, 19);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Kick Everyone to Loggin");
        jButton16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(10, 387, 282, 19);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Turn OFF Server");
        jButton17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(10, 427, 282, 19);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Everyone to Henesys");
        jButton18.setToolTipText("");
        jButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(10, 456, 282, 19);

        serverMessage.setBackground(new java.awt.Color(0, 0, 0));
        serverMessage.setForeground(new java.awt.Color(255, 255, 255));
        serverMessage.setText("server top message");
        serverMessage.setToolTipText("");
        serverMessage.setBorder(null);
        serverMessage.setMaximumSize(new java.awt.Dimension(6, 21));
        serverMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverMessageActionPerformed(evt);
            }
        });
        getContentPane().add(serverMessage);
        serverMessage.setBounds(22, 122, 273, 14);

        Chat.setBackground(new java.awt.Color(0, 0, 0));
        Chat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Chat.setForeground(new java.awt.Color(255, 255, 255));
        Chat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Chat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 97, 338, 480);

        jLabel16.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("<Live Server Chat Log>");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(820, 70, 171, 15);

        mesos.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        mesos.setForeground(new java.awt.Color(255, 204, 0));
        mesos.setText("Server Meso : ");
        getContentPane().add(mesos);
        mesos.setBounds(760, 10, 311, 17);

        realcash.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        realcash.setForeground(new java.awt.Color(0, 255, 0));
        realcash.setText("Server Donation Point : ");
        getContentPane().add(realcash);
        realcash.setBounds(760, 30, 311, 17);

        jLabel15.setFont(new java.awt.Font("DS가변 교양있는글씨 M", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("chiussi");
        jLabel15.setToolTipText("");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(74, 489, 218, 80);
        jLabel15.getAccessibleContext().setAccessibleName("ARCSTORY");

        jLabel17.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("<Online Users>");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(640, 10, 103, 15);

        동시접속자.setBackground(new java.awt.Color(0, 0, 0));
        동시접속자.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        동시접속자.setForeground(new java.awt.Color(255, 255, 255));
        동시접속자.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                동시접속자MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(동시접속자);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(610, 90, 144, 483);

        jLabel18.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("접속자 수 : ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(620, 40, 72, 15);

        접속자수.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        접속자수.setForeground(new java.awt.Color(255, 255, 255));
        접속자수.setText("0");
        getContentPane().add(접속자수);
        접속자수.setBounds(720, 40, 25, 15);

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("UnBan");
        jButton19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(533, 358, 72, 52);

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Reset Opcodes");
        jButton20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(129, 11, 169, 19);

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Refresh");
        jButton21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(610, 60, 144, 19);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/constants/programs/black_background_fabric-wallpaper-2048x1536.jpg"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 1170, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void 환율정보() {
        long meso = 0;
        int realcash = 0;
        try {
            ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0").executeQuery();
            while (ps.next()) {
                meso += ps.getLong("meso");
            }
            ps.close();
            ps = MYSQL.getConnection().prepareStatement("SELECT * FROM storages").executeQuery();
            while (ps.next()) {
                meso += ps.getLong("meso");
            }
            mesos.setText(mesos.getText() + meso + "$");
            ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
            while (ps.next()) {
                realcash += ps.getInt("realcash");
            }
            ps.close();
            this.realcash.setText(this.realcash.getText() + realcash + "$");
        } catch (SQLException ex) {

        }
    }

    public void 벤() {
        try {
            ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
            while (ps.next()) {
                if (ps.getInt("banned") != 0) {
                    BanList.addElement(ps.getString("name"));
                }
            }
            ps.close();
        } catch (SQLException ex) {

        }
    }

    public void 채팅금지() {
        String name = "";
        try {
            ResultSet rs = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0").executeQuery();
            while (rs.next()) {
                if (rs.getString("chatban").equals("true")) {
                    ChatbanList.addElement(rs.getString("name"));
                }
            }
            rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField1.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                hp.gainRC(Integer.parseInt(this.jTextField2.getText()));
                hp.dropMessage(5, "서버로 부터 [" + Integer.parseInt(this.jTextField2.getText()) + "] 후원 포인트를 지급 받으셨습니다.");
                JOptionPane.showMessageDialog(null, jTextField1.getText() + "님에게 후원 포인트를 지급 하였습니다.");
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField3.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                hp.setGMLevel((byte) 6);
                hp.dropShowInfo("GM설정이 되었습니다.");
                JOptionPane.showMessageDialog(null, "GM설정을 하였습니다.");
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField4.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                String a[] = this.jTextField5.getText().split(",");
                int itemid = Integer.parseInt(a[0]);
                short quantity = Short.parseShort(a[1]);
                hp.gainItem(itemid, quantity, false, -1, null);
                hp.dropMessage(1, "아이템을 지급 받으셨습니다.");
                JOptionPane.showMessageDialog(null, "아이템을 지급 하였습니다.");
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField6.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                hp.gainMeso(Long.parseLong(this.jTextField7.getText()), true);
                hp.dropMessage(1, "메소를 지급 받으셨습니다.");
                JOptionPane.showMessageDialog(null, "메소를 지급 하였습니다.");
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void 서버정보불러오기() {
        for (ChannelServer cserv : ChannelServer.getAllInstances()) {
            exp.setText(cserv.getExpRate() + "");
            drop.setText(cserv.getDropRate() + "");
            meso.setText(cserv.getMesoRate() + "");
            serverMessage.setText(cserv.getServerMessage());
            break;
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField8.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                final MapleClient c = null;
                check = true;
                hp.ban(jTextField8.getText(), true, false);
                c.getSession().write(MainPacketCreator.getNPCTalk(2007, (byte) 0, "해당 계정은 지금부터 사용 할 수 없습니다.\r\n(3초 뒤 자동적으로 종료 됩니다.)", "00 00 00 00 00 00", (byte) 2));
                BanList.addElement(hp.getClient().getAccountName());
                Timer.EtcTimer tMan = Timer.EtcTimer.getInstance();
                tMan.schedule(new Runnable() {
                    @Override
                    public void run() {
                        c.disconnect(true, (c.getLoginState() == 4 || c.getLoginState() == 5));
                        c.getSession().close();
                        c.getSession().close();
                    }
                }, 3000);
                JOptionPane.showMessageDialog(null, jTextField8.getText() + "유저를 밴 하였습니다.");
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                hp.setChatban("true");
                hp.dropMessage(1, "채팅 금지를 당하였습니다.");
                JOptionPane.showMessageDialog(null, "채팅 금지를 하였습니다.");
                ChatbanList.addElement(hp.getName());
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        boolean check = false;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            MapleCharacter hp = null;
            hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
            if (hp == null && !check) {
                check = false;
            } else if (hp != null) {
                check = true;
                hp.setChatban("false");
                hp.dropMessage(1, "채팅 금지가 해제 되었습니다.");
                JOptionPane.showMessageDialog(null, "채팅 금지를 해제 하였습니다.");
                ChatList.removeElement(jTextField10.getText());
                초기화();
                return;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (!WorldCommunity.isFreeze) {
            WorldCommunity.isFreeze = true;
            this.jButton8.setText("채팅 녹이기");
            WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "채팅이 얼었습니다."));
            JOptionPane.showMessageDialog(null, "채팅을 얼렸습니다.");
        } else {
            WorldCommunity.isFreeze = false;
            this.jButton8.setText("채팅 얼리기");
            WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "채팅이 녹았습니다."));
            JOptionPane.showMessageDialog(null, "채팅을 녹였습니다.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String b[] = this.hottime.getText().split(",");
        int itemid = Integer.parseInt(b[0]);
        short quantity = Short.parseShort(b[1]);
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
                chr.gainItem(itemid, quantity, false, -1, null);
            }
        }
        WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "핫타임 아이템을 지급 받았습니다."));
        JOptionPane.showMessageDialog(null, "핫타임 아이템을 지급 하였습니다.");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        for (int i = 0; i < ServerConstants.serverCount; i++) {
            ChannelServer.getInstance(i).setExpRate(Integer.parseInt(this.exp.getText()));
            ChannelServer.getInstance(i).setMesoRate((byte) Integer.parseInt(this.meso.getText()));
            ChannelServer.getInstance(i).setDropRate(Integer.parseInt(this.drop.getText()));
            ChannelServer.getInstance(i).setServerMessage(this.serverMessage.getText());
        }
        JOptionPane.showMessageDialog(null, "서버 정보를 변경 하였습니다.");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        공지사항(1, this.noticMessage.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        공지사항(5, this.noticMessage.getText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        공지사항(-1, this.noticMessage.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        공지사항(-2, this.noticMessage.getText());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
                chr.saveToDB(false, false);
            }
        }
        JOptionPane.showMessageDialog(null, "모두 저장을 완료 하였습니다.");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        for (ChannelServer cserv : ChannelServer.getAllInstances()) {
            cserv.getPlayerStorage().disconnectAll();
        }
        JOptionPane.showMessageDialog(null, "모든 플레이어가 로그인 서버로 이동 되었습니다.");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            cs.closeAllMerchant();
            cs.saveAllMerchant();
            cs.getPlayerStorage().disconnectAll();
            //  LoginServer.getInstance().shutdown();
        }
        JOptionPane.showMessageDialog(null, "서버를 종료 하였습니다.");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter hp : cs.getPlayerStorage().getAllCharacters().values()) {
                hp.warp(ServerConstants.mainMap);
            }
        }
        JOptionPane.showMessageDialog(null, "모든 플레이어를 헤네시스로 이동 시켰습니다.");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void 동시접속자MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동시접속자MouseClicked
        try {
            if (동시접속자.getModel() != null) {
                String name = 동시접속자.getModel().getElementAt(동시접속자.getSelectedIndex()).toString();
                jTextField1.setText(name);
                jTextField3.setText(name);
                jTextField4.setText(name);
                jTextField6.setText(name);
                jTextField8.setText(name);
                jTextField10.setText(name);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_동시접속자MouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            Connection con = MYSQL.getConnection();
            PreparedStatement ps = con.prepareStatement("UPDATE accounts SET banned = ?, banreason = ? WHERE name = ?");
            ps.setInt(1, 0);
            ps.setString(2, "");
            ps.setString(3, jTextField8.getText());
            ps.executeUpdate();
            ps.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        BanList.removeElement(jTextField8.getText());
        JOptionPane.showMessageDialog(null, jTextField8.getText() + "님의 게임이용 제한을 해제 하였습니다.");
        초기화();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        SearchToCode.main(null);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void serverMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverMessageActionPerformed

    private void noticMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticMessageActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        SendPacketOpcode.loadOpcode();
        RecvPacketOpcode.loadOpcode();
        System.out.println("[알림] 옵코드 재설정이 완료되었습니다.");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter player : cs.getPlayerStorage().getAllCharacters().values()) {
                if (현재접속자.contains(player.getName())) {
                    동접제거(player.getName());
                    접속자수.setText(String.valueOf((int) (Integer.parseInt(접속자수.getText()) - 1)));
                }
            }
        }
        java.util.Timer timer = new java.util.Timer();
        timer.schedule(new 동접새로고침(), 5000);
    }//GEN-LAST:event_jButton21ActionPerformed

    public String 아이피(String name) throws SQLException {
        String a = "";
        PreparedStatement ps2 = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE name = ?");
        ps2.setString(1, name);
        ResultSet con = ps2.executeQuery();
        while (con.next()) {
            a = con.getString("ip");
        }
        ps2.close();
        con.close();
        return a;
    }

    public void 초기화() {
        String name = "닉네임";
        jTextField1.setText(name);
        jTextField3.setText(name);
        jTextField4.setText(name);
        jTextField6.setText(name);
        jTextField8.setText("닉네임(해제는 계정)");
        jTextField10.setText(name);
    }

    public void 공지사항(int i, String text) {
        if (i == -1) {
            WorldBroadcasting.broadcastMessage(UIPacket.showInfo(text));
        } else if (i == -2) {
            WorldBroadcasting.broadcastMessage(MainPacketCreator.getNPCTalk(2007, (byte) 0, text, "00 00 00 00 00 00", (byte) 0));
        } else {
            WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(i, text));
        }
        JOptionPane.showMessageDialog(null, "[" + text + "] 내용을 모든 플레이어에게 알렸습니다.");
    }

    public static void 동접(String a) {
        try {
            현재접속자.addElement(a);
            동시접속자.setModel(현재접속자);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void 동접제거(String a) {
        현재접속자.removeElement(a);
        동시접속자.setModel(현재접속자);
    }

    public static class 동접새로고침 extends TimerTask {

        @Override
        public void run() {
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                for (MapleCharacter player : cs.getPlayerStorage().getAllCharacters().values()) {
                    if (!현재접속자.contains(player.getName())) {
                        동접(player.getName());
                        접속자수.setText(String.valueOf((int) (Integer.parseInt(접속자수.getText()) + 1)));
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "동접 초기화가 완료 되었습니다!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        UIManager.put("control", new Color(128, 128, 128));
        UIManager.put("info", new Color(128, 128, 128));
        UIManager.put("nimbusBase", new Color(18, 30, 49));
        UIManager.put("nimbusAlertYellow", new Color(248, 187, 0));
        UIManager.put("nimbusDisabledText", new Color(128, 128, 128));
        UIManager.put("nimbusFocus", new Color(115, 164, 209));
        UIManager.put("nimbusGreen", new Color(176, 179, 50));
        UIManager.put("nimbusInfoBlue", new Color(66, 139, 221));
        UIManager.put("nimbusLightBackground", new Color(18, 30, 49));
        UIManager.put("nimbusOrange", new Color(191, 98, 4));
        UIManager.put("nimbusRed", new Color(169, 46, 34));
        UIManager.put("nimbusSelectedText", new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(104, 93, 156));
        UIManager.put("text", new Color(230, 230, 230));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (javax.swing.UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlUnit().setVisible(true);
            }
        });
    }

    public static DefaultListModel ChatList = new DefaultListModel();
    public static DefaultListModel 현재접속자 = new DefaultListModel();
    private DefaultListModel ChatbanList = new DefaultListModel();
    private DefaultListModel BanList = new DefaultListModel();
    private transient ScheduledFuture<?> chattime;
    private int timeo = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList Chat;
    private static javax.swing.JTextField drop;
    private static javax.swing.JTextField exp;
    private javax.swing.JTextField hottime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jjj;
    private static javax.swing.JTextField meso;
    private javax.swing.JLabel mesos;
    private javax.swing.JTextField noticMessage;
    private javax.swing.JLabel realcash;
    private static javax.swing.JTextField serverMessage;
    public static javax.swing.JList 동시접속자;
    public static javax.swing.JLabel 접속자수;
    // End of variables declaration//GEN-END:variables
}
